#!/bin/bash
# script to run the HeliPilot simulator (SITL)
clear
echo "starting up HeliPilot simulator.................."
echo ""
echo "NOTE: TO QUIT THE SIMULATOR press Ctl-C"
echo ""

# check that user locations.txt exists
if [ ! -e ~/.config/helipilot/locations.txt ]; then
    mkdir ~/.config/helipilot && touch ~/.config/helipilot/locations.txt
    echo "adding user locations.txt file..........."
    echo "#NAME=latitude,longitude,absolute-altitude,heading" >> ~/.config/helipilot/locations.txt
    echo "Default=45.4175714,-91.7720328,334,282" >> ~/.config/helipilot/locations.txt
else
    echo "user locations ok!"
    echo ""
fi

ASSUME_YES=false
function maybe_prompt_user() {
    if $ASSUME_YES; then
        return 1
    else
        read -p "$1"
        if [[ $REPLY =~ ^[Nn]$ ]]; then
            return 1
        else
            return 0
        fi
    fi
}

if maybe_prompt_user "Press Enter to continue SIM startup, or to exit use n [n/Y]?" ; then
    while getopts l: option
        do
        case "${option}"
        in
        l) location=${OPTARG};;
    esac
done
echo ""
    if [ -z "$location" ] ; then
        if maybe_prompt_user "Enter a new location for this SIM flight [n/Y]?" ; then
            echo ""
            echo "enter what you wish to call this location"
            echo "Example: Barron"
            echo ""
            read -p 'Location: ' new_location
            echo ""
            echo "enter the details for $new_location seperated by commas with no spaces in the format:"
            echo "latitude,longitude,altitude,initial-heading"
            echo ""
            echo "Example: 45.4175714,-91.7720328,23,270 (NOTE: altitude is MSL in meters)"
            echo ""
            read -p 'Details: ' details
            echo "$new_location=$details" >> ~/.config/helipilot/locations.txt
            git submodule update --recursive
            Tools/autotest/sim_vehicle.py -v Helicopter -f heli -L $new_location
        else
            git submodule update --recursive
            Tools/autotest/sim_vehicle.py -v Helicopter -f heli -L Default
        fi
    else
        git submodule update --recursive
        Tools/autotest/sim_vehicle.py -v Helicopter -f heli -L $location
    fi
else
    echo "Shutting down HeliPilot sim.........."
fi
