#!/bin/bash
# Pixhawk4 - ChibiOS
#
while getopts r:v:c:d: option
    do
        case "${option}"
        in
        r) build_path=${OPTARG};;
        v) version=${OPTARG};;
        c) control=${OPTARG};;
        d) BuildDir=${OPTARG};;
    esac
done

cd $build_path
    ./waf configure --board Pixhawk4
    ./waf heli
cd ./build/Pixhawk4/bin
mv arducopter-heli.bin $version-$control.bin
mv $version-$control.bin $BuildDir
