#!/bin/bash
# Navio2 - 64-bit Linux
#
while getopts r:v:c:d: option
    do
        case "${option}"
        in
        r) build_path=${OPTARG};;
        v) version=${OPTARG};;
        c) control=${OPTARG};;
        d) BuildDir=${OPTARG};;
    esac
done

cd $build_path
    ./waf configure --board linux
    ./waf heli
cd ./build/linux/bin
mv arducopter-heli $version-$control
mv $version-$control $BuildDir
