#!/bin/bash
# Navio2 - 64-bit Linux
#
while getopts r:v:c:d: option
    do
        case "${option}"
        in
        r) build_path=${OPTARG};;
        v) version=${OPTARG};;
        c) control=${OPTARG};;
        d) BuildDir=${OPTARG};;
    esac
done

cd $build_path
    ./waf configure --board navio2
    ./waf heli
cd ./build/navio2/bin
mv firmware-helicopter $version-$control
mv $version-$control $BuildDir
