#!/bin/bash
# Pixhawk1 1MB flash - NuttX
#
while getopts r:v:c:d: option
    do
        case "${option}"
        in
        r) build_path=${OPTARG};;
        v) version=${OPTARG};;
        c) control=${OPTARG};;
        d) BuildDir=${OPTARG};;
    esac
done

cd $build_path
    ./waf configure --board px4-v2
    ./waf heli
cd ./build/px4-v2/bin
mv arducopter-heli.px4 $version-$control.px4
mv $version-$control.px4 $BuildDir
